/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

import classes.Funcionarios;
import static classes.isNumbers.isDouble;
import static classes.isNumbers.isLong;
import enums.Generos;
import java.awt.Color;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Cad_funcionario extends javax.swing.JDialog {

    public static Double salarioMinimo = (double)1500;
    private final Home home;
    private static final String placeHolderSalario = "Acima de R$" + String.valueOf(salarioMinimo) + "(Salário mínimo)";
    private static final String placeHolderCPF = "(11 digitos numéricos)";
    private static final String placeHolderNome = "Nome do funcionário";
    
    
    
    private void HabilitarCadastrar(){
        
        if(!this.txt_nome_funcionario.getText().trim().isEmpty()         &&
           !this.txt_salario_funcionario.getText().trim().isEmpty()      &&
           !this.txt_cpf_funcionario.getText().trim().isEmpty()          &&
           isLong(this.txt_cpf_funcionario.getText().trim())             &&
           isDouble(this.txt_salario_funcionario.getText().trim())       &&
           this.txt_cpf_funcionario.getText().trim().length() == 11      &&
            
            
            Double.valueOf(this.txt_salario_funcionario.getText().trim()) >= salarioMinimo){
           
            this.btn_cadastrar.setEnabled(true);

            
        }else{
            
            this.btn_cadastrar.setEnabled(false);
            
        }
    }
    
    public void AdicionarFuncionario(Home home){
        
        Funcionarios funcionario = new Funcionarios(this.txt_nome_funcionario.getText().toUpperCase(),
                                                    this.txt_cpf_funcionario.getText(),
                                                    Double.valueOf(this.txt_salario_funcionario.getText()),
                                                    Generos.valueOf(this.cb_generos.getSelectedItem().toString()));
        
        home.AddFuncionario(funcionario);
        
        this.txt_nome_funcionario.setText("");
        this.txt_cpf_funcionario.setText("");
        this.txt_salario_funcionario.setText("");
        this.HabilitarPlaceHolderNome();
        this.HabilitarPlaceHolderCPF();
        this.HabilitarPlaceHolderSalario();
        this.HabilitarCadastrar();
        
        JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        
    }
    
    private void HabilitarPlaceHolderNome(){
       if(this.txt_nome_funcionario.getText().trim().isEmpty()){
           
           this.txt_nome_funcionario.setText(placeHolderNome);
           this.txt_nome_funcionario.setForeground(Color.GRAY);
       }
       
        
    }
    
    private void HabilitarPlaceHolderCPF(){
       if(this.txt_cpf_funcionario.getText().trim().isEmpty()){
           
           this.txt_cpf_funcionario.setText(placeHolderCPF);
           this.txt_cpf_funcionario.setForeground(Color.GRAY);
       }
       
        
    }
    
    private void HabilitarPlaceHolderSalario(){
       if(this.txt_salario_funcionario.getText().trim().isEmpty()){
           
           this.txt_salario_funcionario.setText(placeHolderSalario);
           this.txt_salario_funcionario.setForeground(Color.GRAY);
       }
       
       
        
    }
    
    private boolean ValidarCPF(String cpf){
    for(Funcionarios funcionario : this.home.getListaFuncionarios()){
        
        if(funcionario.getCpf().equals(cpf)){
        return false;
                }
    
    }
    
    return true;
    }
    
    public Cad_funcionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.home = (Home)parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_nome = new javax.swing.JLabel();
        txt_nome_funcionario = new javax.swing.JTextField();
        lb_cpf = new javax.swing.JLabel();
        txt_cpf_funcionario = new javax.swing.JTextField();
        lb_salario = new javax.swing.JLabel();
        txt_salario_funcionario = new javax.swing.JTextField();
        lb_genero = new javax.swing.JLabel();
        cb_generos = new javax.swing.JComboBox<>();
        btn_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lb_nome.setText("Nome");

        txt_nome_funcionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nome_funcionarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nome_funcionarioFocusLost(evt);
            }
        });
        txt_nome_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nome_funcionarioKeyReleased(evt);
            }
        });

        lb_cpf.setText("CPF");

        txt_cpf_funcionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cpf_funcionarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cpf_funcionarioFocusLost(evt);
            }
        });
        txt_cpf_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cpf_funcionarioKeyReleased(evt);
            }
        });

        lb_salario.setText("Salário");

        txt_salario_funcionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_salario_funcionarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_salario_funcionarioFocusLost(evt);
            }
        });
        txt_salario_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_salario_funcionarioKeyReleased(evt);
            }
        });

        lb_genero.setText("Gênero");

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.setEnabled(false);
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cadastrar)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_genero)
                    .addComponent(lb_salario)
                    .addComponent(lb_cpf)
                    .addComponent(lb_nome)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_nome_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_cpf_funcionario)
                        .addComponent(txt_salario_funcionario))
                    .addComponent(cb_generos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nome_funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lb_cpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cpf_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lb_salario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_salario_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lb_genero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_generos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(btn_cadastrar)
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         
       for(Generos genero : Generos.values()){
           this.cb_generos.addItem(genero.toString());
       }  
       
       
       this.HabilitarPlaceHolderNome();
       this.HabilitarPlaceHolderCPF();
       this.HabilitarPlaceHolderSalario();
    }//GEN-LAST:event_formWindowOpened

    private void txt_salario_funcionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_salario_funcionarioKeyReleased
        this.HabilitarCadastrar();

    }//GEN-LAST:event_txt_salario_funcionarioKeyReleased

    private void txt_nome_funcionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nome_funcionarioKeyReleased
        this.HabilitarCadastrar();
    }//GEN-LAST:event_txt_nome_funcionarioKeyReleased

    private void txt_cpf_funcionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cpf_funcionarioKeyReleased
        this.HabilitarCadastrar();
    }//GEN-LAST:event_txt_cpf_funcionarioKeyReleased

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        
        if(this.ValidarCPF(this.txt_cpf_funcionario.getText().trim())){
            
            this.AdicionarFuncionario(this.home);
            
        }else{
            
            this.txt_cpf_funcionario.setText("");
            this.txt_cpf_funcionario.requestFocus();
            this.HabilitarCadastrar();
            JOptionPane.showMessageDialog(this, "Funcionário já cadastrado com CPF!", "Erro", JOptionPane.ERROR_MESSAGE);
            
        }
        
                
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void txt_nome_funcionarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nome_funcionarioFocusGained
       
        
        if(!this.txt_nome_funcionario.getText().trim().isEmpty() &&
            this.txt_nome_funcionario.getText().trim().equals(placeHolderNome)){
           
           this.txt_nome_funcionario.setText("");
           this.txt_nome_funcionario.setForeground(Color.BLACK);
       }
    }//GEN-LAST:event_txt_nome_funcionarioFocusGained

    private void txt_nome_funcionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nome_funcionarioFocusLost
       this.HabilitarPlaceHolderNome();
    }//GEN-LAST:event_txt_nome_funcionarioFocusLost

    private void txt_cpf_funcionarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpf_funcionarioFocusGained
    
        if(!this.txt_cpf_funcionario.getText().trim().isEmpty() &&
            this.txt_cpf_funcionario.getText().trim().equals(placeHolderCPF)){
           
           this.txt_cpf_funcionario.setText("");
           this.txt_cpf_funcionario.setForeground(Color.BLACK);
       }
    }//GEN-LAST:event_txt_cpf_funcionarioFocusGained

    private void txt_cpf_funcionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpf_funcionarioFocusLost
       this.HabilitarPlaceHolderCPF();
    }//GEN-LAST:event_txt_cpf_funcionarioFocusLost

    private void txt_salario_funcionarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_salario_funcionarioFocusGained
       if(!this.txt_salario_funcionario.getText().trim().isEmpty() &&
            this.txt_salario_funcionario.getText().trim().equals(placeHolderSalario)){
           
           this.txt_salario_funcionario.setText("");
           this.txt_salario_funcionario.setForeground(Color.BLACK);
       }
    }//GEN-LAST:event_txt_salario_funcionarioFocusGained

    private void txt_salario_funcionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_salario_funcionarioFocusLost
       this.HabilitarPlaceHolderSalario();
    }//GEN-LAST:event_txt_salario_funcionarioFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cad_funcionario dialog = new Cad_funcionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JComboBox<String> cb_generos;
    private javax.swing.JLabel lb_cpf;
    private javax.swing.JLabel lb_genero;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_salario;
    private javax.swing.JTextField txt_cpf_funcionario;
    private javax.swing.JTextField txt_nome_funcionario;
    private javax.swing.JTextField txt_salario_funcionario;
    // End of variables declaration//GEN-END:variables
}
