/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

import classes.Funcionarios;
import enums.Generos;
import enums.atributos_funcionarios;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Mostrar_funcionarios extends javax.swing.JDialog {

    private Home home;
    public Mostrar_funcionarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.home = (Home)parent;
        initComponents();
    }

    public static boolean isDouble(String str) {
    try {
        Double.parseDouble(str);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group_salario = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_funcionarios = new javax.swing.JTable();
        txt_nome_procurar = new javax.swing.JTextField();
        lb_nome = new javax.swing.JLabel();
        txt_cpf_procurar = new javax.swing.JTextField();
        lb_cpf = new javax.swing.JLabel();
        txt_salario_procurar = new javax.swing.JTextField();
        lb_salario = new javax.swing.JLabel();
        lb_genero = new javax.swing.JLabel();
        cb_genero_procurar = new javax.swing.JComboBox<>();
        btn_procurar = new javax.swing.JButton();
        ckbox_genero = new javax.swing.JCheckBox();
        rbtn_maior = new javax.swing.JRadioButton();
        rbtn_igual = new javax.swing.JRadioButton();
        rbtn_menor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        table_funcionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_funcionarios);

        lb_nome.setText("Nome");

        lb_cpf.setText("CPF");

        lb_salario.setText("Salário");

        lb_genero.setText("Gênero");

        cb_genero_procurar.setEnabled(false);

        btn_procurar.setText("Procurar");
        btn_procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procurarActionPerformed(evt);
            }
        });

        ckbox_genero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ckbox_generoMouseReleased(evt);
            }
        });

        btn_group_salario.add(rbtn_maior);
        rbtn_maior.setText("Maior ");

        btn_group_salario.add(rbtn_igual);
        rbtn_igual.setSelected(true);
        rbtn_igual.setText("Igual");

        btn_group_salario.add(rbtn_menor);
        rbtn_menor.setText("Menor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_procurar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_genero)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ckbox_genero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_genero_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lb_salario)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txt_salario_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbtn_maior)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbtn_igual)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbtn_menor))
                        .addComponent(txt_cpf_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_cpf)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_nome_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_nome)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lb_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nome_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_cpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cpf_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_salario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_salario_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtn_maior)
                    .addComponent(rbtn_igual)
                    .addComponent(rbtn_menor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_genero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_genero_procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbox_genero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btn_procurar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
      for(Generos genero : Generos.values()){
           this.cb_genero_procurar.addItem(genero.toString());
       }  

        DefaultTableModel modelo_funcionarios = new DefaultTableModel(atributos_funcionarios.values(), 0);
      
      for(Funcionarios funcionario: this.home.getListaFuncionarios()){
          
          modelo_funcionarios.addRow(funcionario.retornarAtributos());    
      }
      
      
      
      this.table_funcionarios.setModel(modelo_funcionarios);  
     
      
      

      
    }//GEN-LAST:event_formWindowOpened

    private void ckbox_generoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbox_generoMouseReleased
        System.out.println(this.ckbox_genero.isSelected());
        if(this.ckbox_genero.isSelected()){
            this.cb_genero_procurar.setEnabled(true);
        }else{
            this.cb_genero_procurar.setEnabled(false);
        }
    }//GEN-LAST:event_ckbox_generoMouseReleased

    private void btn_procurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procurarActionPerformed
       
       
      LinkedList<Funcionarios> funcionarios = this.home.getListaFuncionarios();
        
      DefaultTableModel model_funcionarios = (DefaultTableModel) this.table_funcionarios.getModel();
      
      for(int ind = 0; ind <= this.table_funcionarios.getRowCount() && this.table_funcionarios.getRowCount() > 0; ind++){
        model_funcionarios.removeRow(0);
      }
      
      
      
      for(int ind = 0; ind < this.home.getListaFuncionarios().size(); ind++){
          
          if(!this.txt_nome_procurar.getText().trim().isEmpty() &&
             !funcionarios.get(ind).getNome().contains(this.txt_nome_procurar.getText().trim().toUpperCase())){
          continue;
          }
          
          if(!this.txt_cpf_procurar.getText().trim().isEmpty() &&
             !funcionarios.get(ind).getCpf().equals(this.txt_cpf_procurar.getText().trim())){
          continue;
          }
          
          if(this.ckbox_genero.isSelected() &&
             !funcionarios.get(ind).getGenero().equals(Generos.valueOf(this.cb_genero_procurar.getSelectedItem().toString()))){
          continue;
          }
          

          if(!this.txt_salario_procurar.getText().trim().isEmpty() &&
             isDouble(this.txt_salario_procurar.getText().trim()) &&
             this.rbtn_maior.isSelected() &&
             funcionarios.get(ind).getSalario() <= Double.valueOf(this.txt_salario_procurar.getText().trim())){
          continue;
          }
          
          if(!this.txt_salario_procurar.getText().trim().isEmpty() &&
             isDouble(this.txt_salario_procurar.getText().trim()) &&
             this.rbtn_igual.isSelected() &&
             (funcionarios.get(ind).getSalario() < Double.valueOf(this.txt_salario_procurar.getText().trim()) ||
              funcionarios.get(ind).getSalario() > Double.valueOf(this.txt_salario_procurar.getText().trim())
              )
            ){
          continue;
          }
          
          if(!this.txt_salario_procurar.getText().trim().isEmpty() &&
             isDouble(this.txt_salario_procurar.getText().trim()) &&
             this.rbtn_menor.isSelected() &&
             funcionarios.get(ind).getSalario() > Double.valueOf(this.txt_salario_procurar.getText().trim())){
          continue;
          }
          
          
          model_funcionarios.addRow(funcionarios.get(ind).retornarAtributos());
          
          
      }
      
      

        
    }//GEN-LAST:event_btn_procurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Mostrar_funcionarios dialog = new Mostrar_funcionarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_group_salario;
    private javax.swing.JButton btn_procurar;
    private javax.swing.JComboBox<String> cb_genero_procurar;
    private javax.swing.JCheckBox ckbox_genero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_cpf;
    private javax.swing.JLabel lb_genero;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_salario;
    private javax.swing.JRadioButton rbtn_igual;
    private javax.swing.JRadioButton rbtn_maior;
    private javax.swing.JRadioButton rbtn_menor;
    private javax.swing.JTable table_funcionarios;
    private javax.swing.JTextField txt_cpf_procurar;
    private javax.swing.JTextField txt_nome_procurar;
    private javax.swing.JTextField txt_salario_procurar;
    // End of variables declaration//GEN-END:variables
}
